<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>67b184bc-e0a9-43c4-aeff-0aace92fdc78</testSuiteGuid>
   <testCaseLink>
      <guid>9d300103-3f52-496a-9696-933e8852980b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Controller</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dcfc3b64-b887-457d-8264-b25fef3ef235</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/credentials</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>dcfc3b64-b887-457d-8264-b25fef3ef235</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>7ee403b2-80c9-46fe-b7d0-cec8f4e4e3ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dcfc3b64-b887-457d-8264-b25fef3ef235</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2ee6449a-4c3c-480a-846c-2bdf6d8c7f89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dcfc3b64-b887-457d-8264-b25fef3ef235</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>b2868f7c-9c21-4864-a9dc-cca3893da7b6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
